# Mensagens de Eleição e Status
MSG_ELECTION = "ELECTION"
MSG_ANSWER = "ANSWER"
MSG_VICTORY = "COORDINATOR_VICTORY"
MSG_HEARTBEAT = "HEARTBEAT"

# Mensagens de Query e 2PC
MSG_QUERY = "EXECUTE_QUERY"
MSG_PREPARE = "PREPARE"
MSG_COMMIT = "COMMIT"
MSG_ROLLBACK = "ROLLBACK"

# Status de Resposta
STATUS_PREPARED = "PREPARED"
STATUS_COMMIT_OK = "COMMIT_OK"
STATUS_FAIL = "FAIL"
STATUS_SUCCESS = "SUCCESS"